name: pyvista
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - meshio==5.0.2
  - pyvista
  - numpy
  # - paraview
  # - paraview=5.11
  # - numpy=1.26.4
  # - paraview=5.10.1=py39h581a1fe_105_qt
  - pip:
    # - meshio[all]==5.0.2
# variables:
# conda env config vars set VAR=1
  # MAMBA_NO_BANNER: '1'
